### ISSUE TITLE
Bug: timeinput behavior

### ISSUE THREAD

**Issue by kyubisation** [lyne-design-system/lyne-components#1806]
- using backspaces misplaces the cursor and produces weird customer behavior
  -  When you have a full input (e.g. `12:00`) and navigate back to hours and hit backspace, it places the cursor in a strange place
- invalid values are exposed (different comparing to datepicker)

**Comment by MarioCastigliano** [comment]
Hi Oliver, we have been investigating about possible solutions and there is a problem with the desired behavior you describe: since we are forwarding the native event from the inner input element, the event.target.value matches the value on the input, that said do you think it could be a viable solution to check on the event.target.valueAsDate property instead? Since it is correctly set to null in the cases you describe.

Please let us know if this is okay with you, or if there is some critical issue that we haven't considered.

**Comment by sbboli** [comment]
@MarioCastigliano works for us, thank you! <3
